### ISSUE TITLE
Imagine using sqlite3 instead of aiosqlite

### ISSUE THREAD

**Issue by dvivufgtb** [DanielOrourke02/Echo#3]
you're using the sqlite3 module for databases why not aiosqlite?
it is not asynchronous and it is blocking io

**Comment by DanielOrourke02** [comment]
Databases aren't my string suit, i saw other developers using sqlite3 for similar economy game discord bots so i just used whatever library they were using.

(sorry might sound stupid) but what are the benefits of using aiosqlite instead of sqlite3?
